services:
  app:
    platform: "linux/amd64"
    image: ghcr.io/mbnsterling/taxpod:latest
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - taxpod-net

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    networks:
      - taxpod-net
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - taxpod-net

networks:
  taxpod-net:
    driver: bridge
